/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"

int *
factorial_1_svc(number *argp, struct svc_req *rqstp)
{
	static int  result;
	
	result =1;	
	for(int i=1;i<=argp->n;i++)
		result *= i;
	printf("Factorial of %d is %d",argp->n,result);
	return &result;
}
