/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "factorial.h"

factorial_out *
factorial_1_svc(factorial_in *inp, struct svc_req *rqstp)
{
	static factorial_out  outp;
	int i;
	i = inp->arg1;
	outp.res1 = 1;
	while(i != 0){
		outp.res1 = outp.res1*i;
		i--;
	}

	return &outp;
}

