/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FACTORIAL_H_RPCGEN
#define _FACTORIAL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct factorial_in {
	long arg1;
};
typedef struct factorial_in factorial_in;

struct factorial_out {
	long res1;
};
typedef struct factorial_out factorial_out;

#define FACT_PROG 0x23451112
#define FACT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define factorial 1
extern  factorial_out * factorial_1(factorial_in *, CLIENT *);
extern  factorial_out * factorial_1_svc(factorial_in *, struct svc_req *);
extern int fact_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define factorial 1
extern  factorial_out * factorial_1();
extern  factorial_out * factorial_1_svc();
extern int fact_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_factorial_in (XDR *, factorial_in*);
extern  bool_t xdr_factorial_out (XDR *, factorial_out*);

#else /* K&R C */
extern bool_t xdr_factorial_in ();
extern bool_t xdr_factorial_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FACTORIAL_H_RPCGEN */
