/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "factorial.h"


void
fact_prog_1(char *host, long int num)
{
	CLIENT *clnt;
	factorial_out  *out;
	factorial_in  in;

#ifndef	DEBUG
	clnt = clnt_create (host, FACT_PROG, FACT_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	in.arg1 = num;
	out = factorial_1(&in, clnt);
	if (out == (factorial_out *) NULL) {
		clnt_perror (clnt, "call failed");
	}else {
		printf("Result: %ld\n", out->res1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	fact_prog_1 (host, atol(argv[2]));
exit (0);
}
